port: {{ default(global.clash.http_port, "7890") }}
socks-port: {{ default(global.clash.socks_port, "7891") }}
allow-lan: {{ default(global.clash.allow_lan, "true") }}
mode: rule
log-level: {{ default(global.clash.log_level, "info") }}
external-controller: :9090

{% if default(request.adg, "true") == "true" or exists("request.adg.port") %}
dns:
  enable: true
  listen: 127.0.0.1:{{ default(request.adg.port, "5450") }}
  ipv6: false
  use-system-hosts: false
  cache-algorithm: arc
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  default-nameserver:
  - 10.22.240.10
  - 10.22.240.8
  - 223.5.5.5
  - 119.29.29.29
  - 1.1.1.1
  - 8.8.8.8
  nameserver:
  - 10.22.240.10
  - 10.22.240.8
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  proxy-server-nameserver:
  - 10.22.240.10
  - 10.22.240.8
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:private,cn,geolocation-cn:
    - 10.22.240.10
    - 10.22.240.8
    - 119.29.29.29
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - 10.22.240.10
    - 10.22.240.8
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
{% endif %}

{% if local.clash.new_field_name == "true" %}
proxies: ~
proxy-groups: ~
rules: ~
{% else %}
Proxy: ~
Proxy Group: ~
Rule: ~
{% endif %}
